<div id='menu-r'></div>

<div id='page-l'>

  <div>
    <!-- Article au hasard -->
    <h3>Lumière sur...</h3>
    <h2>TITRE DE L'ARTICLE<h2>
      <p>Curabitur vulputate, ligula lacinia scelerisque tempor, lacus lacus ornare ante, ac egestas est urna sit amet arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed molestie augue sit amet leo consequat posuere. Vestibulum ante.</p>
      <a href="">...</a>
    <div><a href="">Un autre article</a> | Configurer</div>
  </div>
  <div>
    <h3>Derniers arcticles</h3>
    <div>S'abonner au Flux RSS (Qu'est-ce que c'est?)</div>
    <div><!-- Derniers Artices --></div>
  </div>
  <div>
    <h3>Médiathèque</h3>
  </div>

</div>
