<div class="navbar navbar-fixed-top">
    <div id="menu-top" class="navbar-inner">
      <div class="container-fluid">

        <ul class="nav navbar-nav">
		        <li><img src="http://wiki.belisle.net/sites/wiki.belisle.net/IMG/siteon0.png?1396209443" height="50px;" /></li>
		        <li style="padding: 13px;"><form><input type="text" size="50" style="border-radius: 4px; border: 1px solid #CCCCCC;" /><div style="display: inline-block; padding: 0px 10px;">+</div></form></li>
	      </ul>

        <ul class="nav navbar-nav navbar-right">
          <!-- Notification center -->
		        <li><a href="">N!</a></li>
	          <li style="padding: 15px;">Antoine Turmine</li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b></a>

              <ul id="menu-settings" class="dropdown-menu">
                <li>Vos articles</li>
                <li>Votre sélection</li>
                <hr />
                <li>Votre compte</li>
                <li>Déconnection</li>
              </ul>

          </li>
        </ul>

	  </div>
    </div>
</div>

<div id="render-page">
<?php echo $this->getContent(); ?>
</div>

<footer>
2015 Belisle Solution & Nutrition | <a href="mailto:aturmine@icloud.com">Antoine Turmine</a>.
</footer>
